### PR TITLE
Added New Resources Group

### PR DESCRIPTION
**Pull request by sjfricke**
* Cleaned the "Example" area
* Created a "Resources" section to allow for addition of spec, presentations, etc

### CODE REVIEW

**Comment by vinjn** [comment]
What kinds of links go to `Resources` ? For now it seems you are picking `khronos` only.

**Comment by sjfricke** [comment]
Well I guess the question was really "Where do the Vulkan Specs belong?" because I feel they aren't quite "tutorial" material

**Comment by vinjn** [comment]
How about renaming this section to "Khronos"?

**Comment by sjfricke** [comment]
Ok, ya that sounds way better, will update the PR in a bit

**Comment by sjfricke** [comment]
messed up fork :( need to a new PR

**Pull request closed without merging**
